from __future__ import annotations

import json
import os
from pathlib import Path

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

from hy3_eval.client import Hy3Client, Hy3RequestError
from hy3_eval.dataset import load_dataset, write_dataset
from hy3_eval.evaluator import evaluate_process, reference_solution, run_benchmark, merge_llm_judge
from hy3_eval.models import LLMJudgeResult
from hy3_eval.formula_renderer import render_formula, render_step_formulas
try:
    from hy3_eval.models import error_type_label
except ImportError:
    # Compatibility with a Streamlit hot-reload process that still holds an
    # older models module in memory. A full restart picks up the canonical
    # mapping; this fallback prevents the page from failing during reload.
    _ERROR_TYPE_LABELS = {
        "question_misread": "题意误读", "concept_error": "概念理解错误",
        "calculation_error": "计算错误", "condition_omission": "条件遗漏",
        "jumped_derivation": "跳步推导", "format_error": "格式不符",
        "logical_error": "逻辑推理错误",
        "guessed_option": "猜中选项", "numerical_coincidence": "数值巧合",
        "theorem_misuse_correct_result": "误用定理但得出正确结果",
        "test_case_coincidence": "恰好通过测试用例但实现逻辑存在缺陷",
        "circular_reasoning": "循环论证",
        "domain_convergence_omission": "定义域或收敛条件遗漏",
        "unsupported_claim": "无依据结论",
    }
    def error_type_label(value):
        return _ERROR_TYPE_LABELS.get(value, value) if value else None

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data" / "problems.jsonl"
if not DATA.exists(): write_dataset(DATA)
problems = load_dataset(DATA)
load_dotenv(ROOT / ".env")
has_hy3_key = bool(os.getenv("HY3_API_KEY"))

st.set_page_config(page_title="Hy3 微积分推理评估", page_icon="∫", layout="wide")
st.title("Hy3 微积分推理过程评估器")
st.caption("个人 / 犀牛鸟活动作品 · Hy3 生成可审查解答，确定性工具检查推导")
st.sidebar.subheader("Hy3 连接")
session_key = st.sidebar.text_input(
    "临时 API Key（不会保存）", type="password",
    help="如果没有配置项目根目录 .env，可在这里临时输入；只用于当前 Streamlit 会话。",
)
active_api_key = session_key.strip() or os.getenv("HY3_API_KEY", "").strip()
active_base_url = os.getenv("HY3_BASE_URL", "https://tokenhub.tencentmaas.com/v1")
configured_model = os.getenv("HY3_MODEL", "hy3")
configured_base_url = os.getenv("HY3_BASE_URL", "https://tokenhub.tencentmaas.com/v1")
with st.sidebar.expander("API 参数", expanded=False):
    endpoint_override = st.text_input("Endpoint", value=configured_base_url,
        help="填写 TokenHub 的 API base_url，不要填写控制台 URL 或 regionId 参数。")
    model_override = st.text_input("模型名", value=configured_model,
        help="按 TokenHub curl 示例填写模型名，当前示例为 hy3。")
active_base_url = endpoint_override.strip().rstrip("/") or configured_base_url
active_model = model_override.strip() or configured_model
if active_api_key:
    source = "当前会话 Key" if session_key.strip() else ".env Key"
    st.info(f"Hy3 已配置（{source}） · {active_model} · 尚未验证连接")
else:
    st.warning("当前未检测到 HY3_API_KEY：页面只能运行离线参考演示，不是 Hy3 生成结果。请在项目根目录 .env 中填写 Key 后重启服务。")

def show_diagnostic(diagnostic):
    status = "连接成功" if diagnostic.status == "ok" else "连接失败"
    st.write(f"**{status}** · 类型：`{diagnostic.kind}` · Endpoint：`{diagnostic.endpoint}` · 模型：`{diagnostic.model}`")
    st.write(f"耗时：{diagnostic.elapsed_ms} ms · 自动重试：{diagnostic.retry_count} 次")
    st.write(diagnostic.message)
    if diagnostic.hint: st.info(f"建议：{diagnostic.hint}")

def _pct(value):
    return "暂无" if value is None else f"{value:.1%}"


def _validation_display_metrics(data: dict) -> dict:
    """Backfill audit counts when opening a report generated by an older app.

    Reports are persisted as JSON, so users may open a pre-upgrade report that
    does not yet contain the new explicit denominators.  Deriving them from
    the per-sample rows keeps the result page truthful without requiring users
    to rerun the benchmark merely to see the audit details.
    """
    rows = data.get("validation_results", []) or []
    wrong = [r for r in rows if r.get("kind") == "wrong_answer"]
    answer_correct = [r for r in rows if r.get("final_answer_status") == "valid"]
    wrong_detected = sum(bool(r.get("first_error_detected")) for r in wrong)
    wrong_localized = sum(bool(r.get("first_error_localized")) for r in wrong)
    answer_correct_flagged = sum(not r.get("process_correct_predicted", True) for r in answer_correct)
    answer_correct_false_positive = sum(
        r.get("human_review") != "真实问题" and not r.get("process_correct_predicted", True)
        for r in answer_correct
    )
    values = {
        "validation_wrong_answer_total": len(wrong),
        "validation_wrong_answer_detected_count": wrong_detected,
        "validation_wrong_answer_localized_count": wrong_localized,
        "validation_answer_correct_total": len(answer_correct),
        "validation_answer_correct_flagged_count": answer_correct_flagged,
        "validation_answer_correct_true_problem_count": sum(r.get("human_review") == "真实问题" for r in answer_correct),
        "validation_answer_correct_false_positive_count": answer_correct_false_positive,
        "validation_answer_correct_precision": (
            (answer_correct_flagged - answer_correct_false_positive) / answer_correct_flagged
            if answer_correct_flagged else None
        ),
        "validation_answer_correct_false_positive_rate": (
            answer_correct_false_positive / len(answer_correct)
            if answer_correct else None
        ),
        "validation_answer_correct_false_positive_share": (
            answer_correct_false_positive / answer_correct_flagged
            if answer_correct_flagged else None
        ),
    }
    return {key: data.get(key) if data.get(key) is not None else value for key, value in values.items()}


def _show_formula(title: str, display) -> None:
    st.caption(title)
    if display.latex:
        st.latex(display.latex)
    else:
        st.code(display.raw or "（空）", language=None)
        st.caption("公式未解析，已保留原文显示；这不会改变数学校验结果。")
    if display.unicode:
        st.caption(f"纯文本：{display.unicode}")

if st.sidebar.button("测试 Hy3 连接", disabled=not bool(active_api_key)):
    diagnostic = Hy3Client(api_key=active_api_key, base_url=active_base_url, model=active_model).test_connection()
    st.session_state["hy3_diagnostic"] = diagnostic.model_dump()
    if diagnostic.status == "ok": st.sidebar.success("连接测试通过")
    else: st.sidebar.error(f"连接测试失败：{diagnostic.kind}")
if "hy3_diagnostic" in st.session_state:
    with st.sidebar.expander("最近一次连接诊断", expanded=True):
        from hy3_eval.models import ConnectionDiagnostic
        show_diagnostic(ConnectionDiagnostic.model_validate(st.session_state["hy3_diagnostic"]))
mode = st.sidebar.radio("工作台", ["单题评估", "批量评测", "结果分析"])

if mode == "单题评估":
    options = {f"{p.id} · {p.difficulty} · {p.prompt}": p for p in problems}
    selected = options[st.selectbox("选择题目", list(options))]
    st.info(f"题型：{selected.category}｜难度：{selected.difficulty}｜知识点：{', '.join(selected.tags)}")
    online_available = bool(active_api_key)
    offline = st.checkbox("使用离线参考答案演示（不调用 Hy3）", value=not online_available,
                          disabled=not online_available,
                          help="正式演示应关闭此选项并调用 Hy3。没有 API Key 时只能使用离线参考答案。")
    use_judge = st.checkbox("启用 Hy3 二次过程评审", value=online_available, disabled=not online_available,
                            help="主请求生成解答后，再让 Hy3 以评审身份检查首错步骤、错误类型和答案正确但过程不成立的情况。")
    if st.button("开始评估", type="primary"):
        try:
            client = None if offline else Hy3Client(api_key=active_api_key, base_url=active_base_url, model=active_model)
            solution = reference_solution(selected) if offline else client.solve(selected)
            result = evaluate_process(selected, solution)
            if not offline and use_judge:
                try:
                    judge = client.judge_process(selected, solution)
                    result = merge_llm_judge(result, judge)
                except Hy3RequestError as exc:
                    st.warning(f"Hy3 二次评审未完成：{exc.diagnostic.message}；保留规则校验结果。")
            if offline:
                st.info("来源：离线参考答案。配置 HY3_API_KEY 后取消离线选项，才能展示 Hy3 的真实生成过程。")
            else:
                st.success("来源：Hy3 在线生成。以下步骤是模型返回的结构化可审查解答，不是隐藏思维链。")
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("最终答案", "正确" if result.final_answer.status == "valid" else "待检查")
            c2.metric("过程结论", "成立" if result.process_correct else ("已证实错误" if result.review_status == "invalid" else "需要复核"))
            c3.metric("首个错误步骤", result.first_error_step or "无")
            c4.metric("首个待复核", result.first_review_step or "无")
            if result.answer_correct_but_process_invalid: st.warning("最终答案正确，但过程无法支撑该结论")
            if solution.method_summary:
                st.subheader("解题方法概述")
                st.write(solution.method_summary)
            if solution.assumptions:
                st.subheader("前提与条件")
                for assumption in solution.assumptions:
                    st.markdown(f"- {assumption}")
            st.subheader("完整解答过程")
            for step, assessment in zip(solution.steps, result.steps):
                label = {"valid": "✅ 已验证", "invalid": "❌ 已证实错误", "uncertain": "⚠️ 需要复核"}[assessment.status]
                with st.expander(f"步骤 {step.number} · {label}", expanded=True):
                    before_display, after_display = render_step_formulas(step, selected.variable)
                    _show_formula("变换前", before_display)
                    _show_formula("变换后", after_display)
                    with st.expander("复制文本 / 查看原始数据", expanded=False):
                        st.text(f"变换前（Unicode）：{before_display.unicode}")
                        st.text(f"变换后（Unicode）：{after_display.unicode}")
                        st.code(json.dumps({
                            "expression_before": step.expression_before,
                            "expression_after": step.expression_after,
                            "latex_before": step.latex_before,
                            "latex_after": step.latex_after,
                            "parse_status_before": before_display.parse_status,
                            "parse_status_after": after_display.parse_status,
                        }, ensure_ascii=False, indent=2), language="json")
                    st.write(step.explanation)
                    if step.theorem: st.caption(f"定理：{step.theorem}；条件：{step.condition or '未说明'}")
                    if assessment.evidence: st.write(assessment.evidence)
                    for issue in assessment.issues:
                        message = f"{error_type_label(issue.error_type) or '过程问题'} · `{issue.code}`\n\n{issue.evidence}"
                        if issue.affected: message += "\n\n该问题可能受前序错误影响。"
                        (st.error if issue.status == "invalid" else st.warning)(message)
            st.subheader("规则校验")
            for check in result.rule_checks:
                icon = {"valid": "✅", "invalid": "❌", "uncertain": "⚠️"}[check.status]
                st.write(f"{icon} **{check.message}**：{check.evidence}")
            if result.llm_judge:
                st.subheader("Hy3 二次过程评审")
                judge = result.llm_judge
                judge_label = {"verified": "过程整体正确", "invalid": "发现过程问题", "needs_review": "需要人工复核"}[judge.status]
                st.write(f"**评审结论：{judge_label}**")
                if judge.error_step_index >= 0:
                    st.write(f"评审首错步骤：第 {judge.error_step_index + 1} 步")
                if judge.error_type:
                    st.write(f"评审错误类型：{error_type_label(judge.error_type) or judge.error_type}")
                st.write(f"是否答案正确但过程不成立：{'是' if judge.is_lucky_guess else '否'}")
                if judge.explanation:
                    st.caption(f"评审依据：{judge.explanation}")
            st.subheader("过程评估结论")
            summary = result.process_summary
            if summary:
                if summary.first_error_step is not None:
                    st.error(summary.explanation)
                    st.write(f"**错误开始于第 {summary.first_error_step} 步**")
                    st.write(f"**主要错误类型：{summary.primary_error_type or '未分类'}**")
                    affected = [str(a.number) for a in result.steps if a.affected]
                    if affected:
                        st.caption(f"后续步骤 {', '.join(affected)} 受前序错误影响，不重复计为首错。")
                elif summary.first_review_step is not None:
                    st.warning(summary.explanation)
                    st.write(f"**首个待复核步骤：第 {summary.first_review_step} 步**")
                    st.write(f"**待复核类型：{summary.primary_error_type or '未分类'}**")
                else:
                    st.success(summary.explanation)
                if summary.error_types:
                    st.write(f"**全部错误类型：{'、'.join(summary.error_types)}**")
            with st.expander("题集依据与自动校验", expanded=False):
                st.write(f"来源：{selected.source}")
                st.write(f"构造方式：{selected.construction}")
                st.write(f"分层依据：{selected.metadata.get('difficulty_rationale', '按知识点数量、定理条件和定义域/收敛性复杂度分层')}")
                st.write(f"知识点：{', '.join(selected.tags)}")
                st.write("自动判定：最终答案使用符号等价/文字规则；步骤使用导数恒等式、积分求导回代、极限回代及条件规则。无法确定时显示‘需要复核’，不会冒充错误。")
        except Hy3RequestError as exc:
            st.error("Hy3 请求未完成")
            show_diagnostic(exc.diagnostic)
        except Exception as exc:
            st.error(f"应用错误：{exc}")

elif mode == "批量评测":
    limit = st.slider("题目数量", 1, len(problems), min(9, len(problems)))
    online_available = bool(active_api_key)
    offline = st.checkbox("离线参考答案（不调用 Hy3）", value=not online_available, disabled=not online_available)
    if st.button("运行批量评测", type="primary"):
        report = run_benchmark(problems, client=Hy3Client(api_key=active_api_key, base_url=active_base_url, model=active_model), offline=offline, limit=limit)
        st.session_state["report"] = report.model_dump()
        st.success(f"完成 {report.completed}/{report.total} 题，API 失败 {report.api_failures} 题")
        st.json({"最终答案准确率": report.final_answer_accuracy,
                 "过程正确率": report.process_accuracy,
                 "确定性步骤错误率": report.deterministic_error_rate,
                 "待审查步骤比例": report.uncertain_process_rate,
                 "答案正确但过程无效": report.answer_correct_process_invalid_rate,
                 "验证样本首错检测率": report.validation_first_error_detection_rate,
                 "验证样本首错定位准确率": report.validation_first_error_localization_accuracy,
                 "验证样本答案正确样本误报率": report.validation_false_positive_rate,
                 "答案错误样本实际首错定位数": report.validation_wrong_answer_localized_count,
                 "答案错误样本总数": report.validation_wrong_answer_total,
                 "答案正确样本误报数": report.validation_answer_correct_false_positive_count,
                 "答案正确样本总数": report.validation_answer_correct_total})

else:
    report_path = ROOT / "reports" / "latest_benchmark.json"
    if "report" in st.session_state: data = st.session_state["report"]
    elif report_path.exists(): data = json.loads(report_path.read_text(encoding="utf-8"))
    else: data = None
    if not data:
        st.info("请先在批量评测页运行一次实验。")
    else:
        validation_metrics = _validation_display_metrics(data)
        c1, c2, c3 = st.columns(3)
        c1.metric("最终答案准确率", f"{data['final_answer_accuracy']:.1%}")
        c2.metric("过程正确率", f"{data['process_accuracy']:.1%}")
        c3.metric("API 失败", data["api_failures"])
        st.metric("答案正确但过程无效", f"{data.get('answer_correct_process_invalid_rate', 0):.1%}")
        v1, v2, v3 = st.columns(3)
        v1.metric("首错检测率（答案错误样本）", _pct(data.get("validation_first_error_detection_rate")))
        v2.metric("首错定位准确率（答案错误样本）", _pct(data.get("validation_first_error_localization_accuracy")))
        v3.metric("答案正确样本误报率", _pct(validation_metrics.get("validation_answer_correct_false_positive_rate")))
        if data.get("validation_total"):
            st.caption(f"有效性验证样本：{data['validation_total']} 条（正确、答案错误、答案正确但过程错误各一组）。")
        if validation_metrics.get("validation_wrong_answer_total") is not None:
            st.caption(
                "答案错误样本："
                f"{validation_metrics.get('validation_wrong_answer_total', 0)} 条，"
                f"检测到过程问题 {validation_metrics.get('validation_wrong_answer_detected_count', 0)} 条，"
                f"定位到实际首错步骤 {validation_metrics.get('validation_wrong_answer_localized_count', 0)} 条。"
            )
        if validation_metrics.get("validation_answer_correct_total") is not None:
            st.caption(
                "正确答案样本抽检："
                f"{validation_metrics.get('validation_answer_correct_total', 0)} 条；被判为过程有问题 "
                f"{validation_metrics.get('validation_answer_correct_flagged_count', 0)} 条；人工确认真实问题 "
                f"{validation_metrics.get('validation_answer_correct_true_problem_count', 0)} 条；误报 "
                f"{validation_metrics.get('validation_answer_correct_false_positive_count', 0)} 条。"
            )
            if validation_metrics.get("validation_answer_correct_false_positive_share") is not None:
                st.caption(
                    "误报率口径：误报 ÷ 全部正确答案样本 = "
                    f"{_pct(validation_metrics.get('validation_answer_correct_false_positive_rate'))}；"
                    "在被判有问题样本中的误报占比 = "
                    f"{_pct(validation_metrics.get('validation_answer_correct_false_positive_share'))}。"
                )
        if data.get("performance_decline_layer"):
            st.warning(f"能力临界点：{data['performance_decline_layer']} 难度层开始明显下降（依据实际评测过程正确率低于 70% 或较上一层下降至少 15 个百分点）。")
        elif data.get("validation_by_difficulty"):
            st.info("有效性验证中未发现满足阈值的明显下降难度层。")
        st.caption(f"确定性步骤错误率：{data.get('deterministic_error_rate', 0):.1%} · 待审查步骤比例：{data.get('uncertain_process_rate', 0):.1%}。待审查不等于数学错误。")
        rows = []
        for name, metrics in data.get("by_difficulty", {}).items(): rows.append({"难度": name, **metrics})
        if rows:
            st.subheader("按难度")
            st.dataframe(pd.DataFrame(rows), use_container_width=True)
        st.subheader("错误类型分布")
        # 按需求使用“横轴＝错误类型、纵轴＝发生次数”的柱状图。
        # DataFrame 索引作为 X 轴分类，列值作为 Y 轴数值。
        error_rows = [
            {"错误类型": error_type_label(error_type) or error_type, "错误发生次数": count}
            for error_type, count in data.get("error_type_distribution", {}).items()
            if count
        ]
        if error_rows:
            error_data = (
                pd.DataFrame(error_rows)
                .sort_values("错误发生次数", ascending=False)
                .set_index("错误类型")
            )
            st.bar_chart(
                error_data,
                horizontal=False,
                x_label="错误类型",
                y_label="错误发生次数",
            )
        else:
            st.info("暂无错误类型数据。")
        st.subheader("逐题错误明细")
        detail_rows = []
        for item in data.get("results", []):
            summary = item.get("process_summary") or {}
            final = item.get("final_answer", {})
            assessments = item.get("steps", [])
            first_error_number = summary.get("first_error_step")
            first_error_assessment = next((step for step in assessments if step.get("number") == first_error_number), None)
            detail_rows.append({
                "题号": item.get("problem_id", ""),
                "题型": next((p.category for p in problems if p.id == item.get("problem_id")), ""),
                "难度": next((p.difficulty for p in problems if p.id == item.get("problem_id")), ""),
                "最终答案状态": "正确" if final.get("status") == "valid" else ("错误" if final.get("status") == "invalid" else "待复核"),
                "过程结论": "成立" if item.get("process_correct") else ("未完成评估" if item.get("api_failed") else ("已证实错误" if item.get("review_status") == "invalid" else "需要复核")),
                "首个错误步骤": summary.get("first_error_step") or "无",
                "首个待复核步骤": summary.get("first_review_step") or "无",
                "主要错误类型": summary.get("primary_error_type") or "无",
                "全部错误类型": "、".join(summary.get("error_types", [])) or "无",
                "答案正确但过程错误": "是" if item.get("answer_correct_but_process_invalid") else "否",
                "标准答案公式": final.get("expected_unicode") or final.get("expected", ""),
                "Hy3答案公式": final.get("actual_unicode") or final.get("actual", ""),
                "首错前公式": (first_error_assessment or {}).get("unicode_before", ""),
                "首错后公式": (first_error_assessment or {}).get("unicode_after", ""),
                "公式解析状态": final.get("formula_parse_status") or "未知",
                "规则校验": "；".join(f"{check.get('message', '')}：{check.get('evidence', '')}" for check in item.get("rule_checks", [])) or "未记录",
            })
        if detail_rows:
            st.dataframe(pd.DataFrame(detail_rows), use_container_width=True, hide_index=True)
            st.caption("详细公式保留在逐题评估页面；表格使用纯文本表示，避免复杂分式造成横向溢出。")
        validation_rows = data.get("validation_results", [])
        if validation_rows:
            st.subheader("过程评估器有效性验证明细")
            st.dataframe(pd.DataFrame([{
                "题号": row.get("problem_id"), "样本组": {"correct": "正确样本", "wrong_answer": "答案错误样本", "correct_answer_wrong_process": "答案正确但过程错误"}.get(row.get("kind"), row.get("kind")),
                "实际首错步骤": row.get("actual_first_error_step", row.get("expected_first_error_step")) or "无",
                "预测问题步骤": row.get("predicted_issue_step") or "无",
                "预测确定性首错": row.get("predicted_deterministic_error_step") or "无",
                "首个待复核步骤": row.get("predicted_first_review_step") or "无",
                "是否检测到问题": "是" if row.get("first_error_detected") else "否", "是否定位正确": "是" if row.get("first_error_localized") else "否",
                "标准错误类型": "、".join(row.get("expected_error_types", [])) or "无", "预测错误类型": "、".join(row.get("predicted_error_types", [])) or "无",
                "人工审核": row.get("human_review"), "是否误报": "是" if row.get("false_positive") else "否",
            } for row in validation_rows]), use_container_width=True, hide_index=True)
            by_kind = data.get("validation_by_kind", {})
            if by_kind:
                st.caption("分组指标：" + "；".join(f"{k} 检测率 {v.get('process_issue_detection_rate', 0):.1%}、误报率 {v.get('false_positive_rate', 0):.1%}" for k, v in by_kind.items()))
            difficulty_rows = [{"难度": name, **metrics} for name, metrics in data.get("validation_by_difficulty", {}).items()]
            if difficulty_rows:
                st.subheader("有效性验证分层结果")
                st.dataframe(pd.DataFrame(difficulty_rows), use_container_width=True, hide_index=True)
